"""empty message

Revision ID: 44db11f560e1
Revises: 74f37cc50650
Create Date: 2021-05-27 19:12:05.867695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44db11f560e1'
down_revision = '74f37cc50650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_created_on'), 'contact', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_created_on'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
